import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { requireUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { ensureInvoice } from "@/lib/invoices";
import { formatMoney } from "@/lib/commerce";

export const metadata={title:"Invoice"};
export default async function Page({params}:{params:Promise<{id:string}>}){const user=await requireUser();const{id}=await params;const booking=await db.booking.findUnique({where:{id},include:{studio:true,creator:true,room:true}});if(!booking)notFound();const allowed=user.role==="ADMIN"||(user.role==="CREATOR"&&booking.creatorId===user.id)||(user.role==="STUDIO_OWNER"&&booking.studio.ownerId===user.id);if(!allowed)redirect("/dashboard");if(!["CONFIRMED","COMPLETED","CANCELLED","DISPUTED"].includes(booking.status))redirect("/dashboard");const invoice=await ensureInvoice(booking.id);if(!invoice)notFound();return <main className="min-h-screen bg-white text-black"><section className="mx-auto max-w-3xl px-6 py-12"><div className="flex items-start justify-between gap-6"><div><div className="text-4xl font-black">36</div><p className="mt-2 text-sm text-zinc-500">Creative Studio Marketplace</p></div><div className="text-right"><h1 className="text-3xl font-black">INVOICE</h1><p className="mt-1 text-sm text-zinc-500">{invoice.number}</p></div></div><div className="mt-10 grid gap-8 sm:grid-cols-2"><div><b>Seller</b><p className="mt-2 text-sm">{invoice.sellerName}</p>{invoice.sellerIce&&<p className="text-sm text-zinc-600">ICE: {invoice.sellerIce}</p>}{invoice.sellerTaxId&&<p className="text-sm text-zinc-600">Tax ID: {invoice.sellerTaxId}</p>}</div><div><b>Bill to</b><p className="mt-2 text-sm">{invoice.buyerName}</p><p className="text-sm text-zinc-600">{invoice.buyerEmail}</p></div></div><div className="mt-10 border-y border-zinc-200 py-5"><div className="flex justify-between"><span>{booking.studio.name} · {booking.room.name}</span><b>{formatMoney(invoice.subtotalMad, invoice.currency)}</b></div>{invoice.discountMad>0&&<div className="mt-2 flex justify-between text-sm text-zinc-600"><span>Discount</span><span>-{formatMoney(invoice.discountMad, invoice.currency)}</span></div>}{invoice.taxAmountMad>0&&<div className="mt-2 flex justify-between text-sm text-zinc-600"><span>Tax {(invoice.taxBps/100).toFixed(2)}%</span><span>{formatMoney(invoice.taxAmountMad, invoice.currency)}</span></div>}<div className="mt-4 flex justify-between text-xl font-black"><span>Total</span><span>{formatMoney(invoice.totalMad, invoice.currency)}</span></div></div><p className="mt-6 text-xs text-zinc-500">Issued {invoice.issuedAt.toLocaleDateString("en-US",{dateStyle:"medium"})} · Booking {booking.id}</p><Link href={user.role==="STUDIO_OWNER"?`/owner/bookings/${booking.id}`:`/creator/bookings/${booking.id}`} className="mt-8 inline-flex rounded-full border border-zinc-300 px-4 py-2 text-sm font-bold">Back to booking</Link><p className="mt-6 text-xs text-zinc-400">Use your browser’s Print command to save this invoice as PDF.</p></section></main>}
