import { NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { db } from "@/lib/db";
import { consumeRateLimit, fingerprintFromRequest } from "@/lib/rate-limit";

export const runtime = "nodejs";
const MAX_BYTES=25*1024*1024;
const ALLOWED=new Set(["image/jpeg","image/png","image/webp","application/pdf","audio/mpeg","audio/wav","audio/x-wav","audio/ogg","audio/mp4"]);
export async function POST(request:Request){const user=await getCurrentUser();if(!user)return NextResponse.json({error:"Login required."},{status:401});if(!user.emailVerifiedAt)return NextResponse.json({error:"Verify your email first."},{status:403});const rate=await consumeRateLimit({key:fingerprintFromRequest(request),action:`booking-file:${user.id}`,limit:30,windowSeconds:3600});if(!rate.allowed)return NextResponse.json({error:"Upload limit reached."},{status:429});const form=await request.formData();const bookingId=String(form.get("bookingId")||"");const file=form.get("file");if(!(file instanceof File)||!ALLOWED.has(file.type)||file.size<=0||file.size>MAX_BYTES)return NextResponse.json({error:"Allowed: images, PDF and audio up to 25 MB."},{status:400});const booking=await db.booking.findUnique({where:{id:bookingId},include:{studio:true}});if(!booking)return NextResponse.json({error:"Booking not found."},{status:404});const allowed=user.role==="ADMIN"||booking.creatorId===user.id||booking.studio.ownerId===user.id;if(!allowed)return NextResponse.json({error:"Forbidden."},{status:403});const cloud=process.env.CLOUDINARY_CLOUD_NAME,preset=process.env.CLOUDINARY_UPLOAD_PRESET;if(!cloud||!preset)return NextResponse.json({error:"File storage is not configured."},{status:503});const upload=new FormData();upload.set("file",file);upload.set("upload_preset",preset);upload.set("folder",`36/bookings/${booking.id}`);const res=await fetch(`https://api.cloudinary.com/v1_1/${encodeURIComponent(cloud)}/auto/upload`,{method:"POST",body:upload});const result=await res.json().catch(()=>({}));if(!res.ok||!result.secure_url||!result.public_id)return NextResponse.json({error:"Upload failed."},{status:502});const stored=await db.storedFile.create({data:{ownerId:user.id,studioId:booking.studioId,bookingId:booking.id,kind:"BOOKING_ATTACHMENT",provider:"CLOUDINARY",storageKey:String(result.public_id),url:String(result.secure_url),mimeType:file.type,sizeBytes:BigInt(file.size)}});return NextResponse.json({ok:true,file:{id:stored.id,url:stored.url,mimeType:stored.mimeType,name:file.name}})}
