"use client";
import { useEffect, useState } from "react";

type Result={label:string;latitude:number;longitude:number;city?:string;neighborhood?:string};
export function StudioLocationFields(props:{city:string;neighborhood:string;address:string;latitude:string;longitude:string}){
  const[city,setCity]=useState(props.city);const[neighborhood,setNeighborhood]=useState(props.neighborhood);const[address,setAddress]=useState(props.address);const[lat,setLat]=useState(props.latitude);const[lng,setLng]=useState(props.longitude);const[results,setResults]=useState<Result[]>([]);const[loading,setLoading]=useState(false);
  useEffect(()=>{if(address.trim().length<4){setResults([]);return}const t=setTimeout(async()=>{setLoading(true);const r=await fetch(`/api/geocode?q=${encodeURIComponent(address)}`);const d=await r.json().catch(()=>({results:[]}));setResults(r.ok?d.results||[]:[]);setLoading(false)},350);return()=>clearTimeout(t)},[address]);
  function choose(r:Result){setAddress(r.label);setLat(String(r.latitude));setLng(String(r.longitude));if(r.city)setCity(r.city);if(r.neighborhood)setNeighborhood(r.neighborhood);setResults([])}
  return <><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">City</span><input className="field" name="city" value={city} onChange={e=>setCity(e.target.value)}/></label><label><span className="label">Neighborhood</span><input className="field" name="neighborhood" value={neighborhood} onChange={e=>setNeighborhood(e.target.value)}/></label></div><label className="relative block"><span className="label">Address</span><input className="field" name="address" value={address} onChange={e=>setAddress(e.target.value)} placeholder="Start typing the studio address…" autoComplete="off"/>{loading&&<span className="mt-1 block text-[10px] text-[#8a8a8a]">Searching Morocco…</span>}{results.length>0&&<div className="absolute z-30 mt-1 w-full overflow-hidden rounded-xl border border-[#dddddd] bg-white shadow-2xl">{results.map((r,i)=><button type="button" key={`${r.label}-${i}`} onClick={()=>choose(r)} className="block w-full border-b border-[#ebebeb] px-4 py-3 text-left text-xs text-[#333333] last:border-0 hover:bg-[#f3f3f3]">{r.label}</button>)}</div>}</label><div className="grid gap-4 sm:grid-cols-2"><label><span className="label">Latitude</span><input className="field" name="latitude" type="number" step="0.000001" min="-90" max="90" value={lat} onChange={e=>setLat(e.target.value)}/></label><label><span className="label">Longitude</span><input className="field" name="longitude" type="number" step="0.000001" min="-180" max="180" value={lng} onChange={e=>setLng(e.target.value)}/></label></div></>
}
